In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
#pd.options.display.float_format = '{:.1f}'.format # 지수 변환 방지

In [2]:
data = pd.read_csv('data/train.csv', encoding='CP949')
data.head()

,custid,gender,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,가을_구매건수,겨울_구매건수,봄_구매건수,여름_구매건수,아침_구매건수,저녁_구매건수,점심_구매건수,주구매코너
0,18,0,680100,15,45340,1.7,9,10,26.7,100.0,NaN,9.0,6.0,NaN,NaN,6.0,9.0,화장품
1,21,0,353450,9,39272,1.2,6,8,11.1,37.5,NaN,5.0,4.0,NaN,3.0,NaN,6.0,영캐주얼
2,23,0,5671400,36,157539,2.8,22,16,5.6,37.5,7.0,17.0,12.0,NaN,10.0,11.0,15.0,장신구
3,26,0,1964000,28,70143,1.4,15,14,39.3,28.6,5.0,8.0,15.0,NaN,NaN,18.0,10.0,화장품
4,35,0,885000,5,177000,6.0,5,2,0.0,100.0,NaN,NaN,5.0,NaN,NaN,5.0,NaN,피혁A

In [3]:
test = pd.read_csv('data/test.csv', encoding='CP949')
test.head()

,custid,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,가을_구매건수,겨울_구매건수,봄_구매건수,여름_구매건수,아침_구매건수,저녁_구매건수,점심_구매건수,주구매코너
0,100001,3439000,25,137560,2.2,19,16,12.0,31.2,5.0,4.0,7.0,9.0,13.0,1.0,11.0,장신구
1,100002,2073090,39,53156,1.3,18,29,0.0,20.7,13.0,8.0,10.0,8.0,4.0,10.0,25.0,유아동복
2,100003,1303800,22,59264,1.8,14,12,0.0,41.7,6.0,7.0,3.0,6.0,3.0,1.0,18.0,유아동복
3,100004,6696522,46,145577,1.7,31,22,37.0,50.0,5.0,15.0,9.0,17.0,NaN,4.0,42.0,수입명품
4,100005,1297640,26,49909,2.3,13,9,11.5,22.2,18.0,NaN,5.0,3.0,NaN,NaN,26.0,스포츠

# 데이터 탐색(EDA)

In [4]:
data.corr()

,custid,gender,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,가을_구매건수,겨울_구매건수,봄_구매건수,여름_구매건수,아침_구매건수,저녁_구매건수,점심_구매건수
custid,1.000000,0.262472,0.217251,0.218914,0.117939,0.093048,0.154303,0.212969,-0.017958,-0.162393,0.169628,0.164004,0.189248,0.209086,0.170199,0.025959,0.245526
gender,0.262472,1.000000,0.099137,0.094022,0.072181,-0.020066,0.083988,0.084255,-0.021294,0.020457,0.082396,0.062853,0.073478,0.098237,0.117025,-0.017439,0.098814
총구매액,0.217251,0.099137,1.000000,0.712183,0.376395,0.137335,0.714774,0.617210,-0.048053,-0.048515,0.636912,0.598012,0.621589,0.600210,0.411808,0.375806,0.705898
구매건수,0.218914,0.094022,0.712183,1.000000,-0.057376,-0.037878,0.869075,0.942115,-0.210022,-0.096558,0.890560,0.872558,0.891125,0.879405,0.643542,0.631686,0.944120
평균구매가격,0.117939,0.072181,0.376395,-0.057376,1.000000,0.407556,0.002931,-0.091136,0.189608,0.036426,-0.030972,-0.054408,-0.051558,-0.056996,-0.045784,-0.096015,-0.025700
평균할부개월수,0.093048,-0.020066,0.137335,-0.037878,0.407556,1.000000,-0.002074,-0.076343,0.097727,-0.001625,-0.015512,-0.037181,-0.029433,-0.035267,-0.061617,-0.056620,-0.006523
구매브랜드종류,0.154303,0.083988,0.714774,0.869075,0.002931,-0.002074,1.000000,0.780303,-0.234547,-0.080674,0.753557,0.752453,0.768225,0.732592,0.544562,0.557397,0.809973
내점일수,0.212969,0.084255,0.617210,0.942115,-0.091136,-0.076343,0.780303,1.000000,-0.225363,-0.114795,0.827788,0.820413,0.832312,0.814047,0.603499,0.622984,0.873686
수입상품_구매비율,-0.017958,-0.021294,-0.048053,-0.210022,0.189608,0.097727,-0.234547,-0.225363,1.000000,0.016123,-0.143282,-0.159061,-0.170131,-0.154914,-0.102365,-0.150986,-0.175920
주말방문비율,-0.162393,0.020457,-0.048515,-0.096558,0.036426,-0.001625,-0.080674,-0.114795,0.016123,1.000000,-0.093130,-0.091832,-0.083555,-0.100046,-0.102636,-0.027938,-0.100132
가을_구매건수,0.169628,0.082396,0.636912,0.890560,-0.030972,-0.015512,0.753557,0.827788,-0.143282,-0.093130,1.000000,0.715812,0.728004,0.714070,0.562094,0.545395,0.836476
겨울_구매건수,0.164004,0.062853,0.598012,0.872558,-0.054408,-0.037181,0.752453,0.820413,-0.159061,-0.091832,0.715812,1.000000,0.727993,0.680019,0.539378,0.576646,0.807451
봄_구매건수,0.189248,0.073478,0.621589,0.891125,-0.051558,-0.029433,0.768225,0.832312,-0.170131,-0.083555,0.728004,0.727993,1.000000,0.695559,0.582013,0.551262,0.833013
여름_구매건수,0.209086,0.098237,0.600210,0.879405,-0.056996,-0.035267,0.732592,0.814047,-0.154914,-0.100046,0.714070,0.680019,0.695559,1.000000,0.541327,0.517729,0.839610
아침_구매건수,0.170199,0.117025,0.411808,0.643542,-0.045784,-0.061617,0.544562,0.603499,-0.102365,-0.102636,0.562094,0.539378,0.582013,0.541327,1.000000,0.102727,0.479174
저녁_구매건수,0.025959,-0.017439,0.375806,0.631686,-0.096015,-0.056620,0.557397,0.622984,-0.150986,-0.027938,0.545395,0.576646,0.551262,0.517729,0.102727,1.000000,0.445585
점심_구매건수,0.245526,0.098814,0.705898,0.944120,-0.025700,-0.006523,0.809973,0.873686,-0.175920,-0.100132,0.836476,0.807451,0.833013,0.839610,0.479174,0.445585,1.000000

In [5]:
pd.DataFrame((data.corr()['gender']).sort_values(ascending = False))

             gender
gender     1.000000
custid     0.262472
아침_구매건수    0.117025
총구매액       0.099137
점심_구매건수    0.098814
여름_구매건수    0.098237
구매건수       0.094022
내점일수       0.084255
구매브랜드종류    0.083988
가을_구매건수    0.082396
봄_구매건수     0.073478
평균구매가격     0.072181
겨울_구매건수    0.062853
주말방문비율     0.020457
저녁_구매건수   -0.017439
평균할부개월수   -0.020066
수입상품_구매비율 -0.021294

- 상관계수가 전반적으로 적은 것을 알 수 있음
- 가장 큰 상관계수를 지닌 컬럼은 '아침_구매건수'

In [6]:
pd.crosstab(data['주구매코너'], data['gender'], margins=True)
# gender 0 : 여자, 1 : 남자

gender       0     1   All
주구매코너
가구           6     1     7
가전          13     5    18
기타바이어        9     3    12
니트단품        74    17    91
도자기크리스탈      6     5    11
디자이너부띠끄     38    13    51
문화완구        21    17    38
섬유          75    21    96
수입명품        85    51   136
스포츠        180   121   301
엘레강스캐주얼     60    18    78
영캐주얼       196    50   246
유니캐주얼      301   109   410
유아동복       241   142   383
일반식품       854   452  1306
장신구         52    16    68
정장셔츠        45    45    90
조리욕실        24     4    28
침구수예         7     1     8
캐릭터캐주얼     140    48   188
타운모피         4     2     6
트래디셔널캐주얼    57    34    91
피혁A         46    29    75
피혁B         46    10    56
화장품        899   307  1206
All       3479  1521  5000

- 여성의 경우 화장품>일반식품>유니캐주얼 순으로 구매량이 많음
- 남성의 경우 일반식품>화장품>유아동복 순으로 구매량이 많음

In [7]:
data['gender'].value_counts()

0    3479
1    1521
Name: gender, dtype: int64

In [8]:
print(" -- data의 정보 -- ")
data.info()
print("")
print(" -- test의 정보 -- ")
test.info()

 -- data의 정보 --
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   custid     5000 non-null   int64
 1   gender     5000 non-null   int64
 2   총구매액       5000 non-null   int64
 3   구매건수       5000 non-null   int64
 4   평균구매가격     5000 non-null   int64
 5   평균할부개월수    5000 non-null   float64
 6   구매브랜드종류    5000 non-null   int64
 7   내점일수       5000 non-null   int64
 8   수입상품_구매비율  5000 non-null   float64
 9   주말방문비율     5000 non-null   float64
 10  가을_구매건수    4055 non-null   float64
 11  겨울_구매건수    4103 non-null   float64
 12  봄_구매건수     4311 non-null   float64
 13  여름_구매건수    3978 non-null   float64
 14  아침_구매건수    3558 non-null   float64
 15  저녁_구매건수    4033 non-null   float64
 16  점심_구매건수    4855 non-null   float64
 17  주구매코너      5000 non-null   object
dtypes: float64(10), int64(7), object(1)
memory usage: 703.2+ KB

 -- test의 정보 --
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   custid     5000 non-null   int64
 1   총구매액       5000 non-null   int64
 2   구매건수       5000 non-null   int64
 3   평균구매가격     5000 non-null   int64
 4   평균할부개월수    5000 non-null   float64
 5   구매브랜드종류    5000 non-null   int64
 6   내점일수       5000 non-null   int64
 7   수입상품_구매비율  5000 non-null   float64
 8   주말방문비율     5000 non-null   float64
 9   가을_구매건수    4052 non-null   float64
 10  겨울_구매건수    4089 non-null   float64
 11  봄_구매건수     4319 non-null   float64
 12  여름_구매건수    4009 non-null   float64
 13  아침_구매건수    3608 non-null   float64
 14  저녁_구매건수    3975 non-null   float64
 15  점심_구매건수    4861 non-null   float64
 16  주구매코너      5000 non-null   object
dtypes: float64(10), int64(6), object(1)
memory usage: 664.2+ KB

- 구매건수 컬럼들에서 NaN 값이 존재하는걸 알 수 있음
- 구매건수가 0일때 NaN 값이 생기므로 NaN 값을 0으로 채워줄 것
- 주구매코너 컬럼의 데이터 형태가 object이므로 수치형 컬럼으로 변환할 것
- 남녀 비율이 맞지 않아 데이터 비대칭 현상이 발생할 수 있으므로 셈플링을 통해 이를 해결할 것

# 데이터 전처리

### 결측치 처리

In [9]:
data.isnull().sum()

custid          0
gender          0
총구매액            0
구매건수            0
평균구매가격          0
평균할부개월수         0
구매브랜드종류         0
내점일수            0
수입상품_구매비율       0
주말방문비율          0
가을_구매건수       945
겨울_구매건수       897
봄_구매건수        689
여름_구매건수      1022
아침_구매건수      1442
저녁_구매건수       967
점심_구매건수       145
주구매코너           0
dtype: int64

In [10]:
data = data.fillna(0)
data.head()

,custid,gender,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,가을_구매건수,겨울_구매건수,봄_구매건수,여름_구매건수,아침_구매건수,저녁_구매건수,점심_구매건수,주구매코너
0,18,0,680100,15,45340,1.7,9,10,26.7,100.0,0.0,9.0,6.0,0.0,0.0,6.0,9.0,화장품
1,21,0,353450,9,39272,1.2,6,8,11.1,37.5,0.0,5.0,4.0,0.0,3.0,0.0,6.0,영캐주얼
2,23,0,5671400,36,157539,2.8,22,16,5.6,37.5,7.0,17.0,12.0,0.0,10.0,11.0,15.0,장신구
3,26,0,1964000,28,70143,1.4,15,14,39.3,28.6,5.0,8.0,15.0,0.0,0.0,18.0,10.0,화장품
4,35,0,885000,5,177000,6.0,5,2,0.0,100.0,0.0,0.0,5.0,0.0,0.0,5.0,0.0,피혁A

In [11]:
data.isnull().sum()

custid       0
gender       0
총구매액         0
구매건수         0
평균구매가격       0
평균할부개월수      0
구매브랜드종류      0
내점일수         0
수입상품_구매비율    0
주말방문비율       0
가을_구매건수      0
겨울_구매건수      0
봄_구매건수       0
여름_구매건수      0
아침_구매건수      0
저녁_구매건수      0
점심_구매건수      0
주구매코너        0
dtype: int64

### 범주형 데이터 변환

In [12]:
data['주구매코너']

0           화장품
1          영캐주얼
2           장신구
3           화장품
4           피혁A
         ...
4995       일반식품
4996    디자이너부띠끄
4997        화장품
4998        피혁A
4999       일반식품
Name: 주구매코너, Length: 5000, dtype: object

In [13]:
# 범주형 데이터 변환
obj = ['주구매코너']
data[obj] = data[obj].apply(lambda x: x.astype('category').cat.codes)

In [14]:
data['주구매코너']

0       24
1       11
2       15
3       24
4       22
        ..
4995    14
4996     5
4997    24
4998    22
4999    14
Name: 주구매코너, Length: 5000, dtype: int8

### 파생변수 생성

In [15]:
pd.DataFrame((data.corr()['아침_구매건수']).sort_values(ascending = False))

            아침_구매건수
아침_구매건수    1.000000
구매건수       0.672721
내점일수       0.638138
봄_구매건수     0.615851
가을_구매건수    0.607713
여름_구매건수    0.587149
구매브랜드종류    0.582657
겨울_구매건수    0.581196
점심_구매건수    0.526168
총구매액       0.456158
custid     0.199936
저녁_구매건수    0.143963
gender     0.127779
평균구매가격    -0.040362
평균할부개월수   -0.047450
주말방문비율    -0.113193
주구매코너     -0.116397
수입상품_구매비율 -0.133133

In [16]:
pd.DataFrame((data.corr()['구매건수']).sort_values(ascending = False))

               구매건수
구매건수       1.000000
점심_구매건수    0.945027
내점일수       0.942115
가을_구매건수    0.896969
봄_구매건수     0.895580
여름_구매건수    0.883784
겨울_구매건수    0.879652
구매브랜드종류    0.869075
총구매액       0.712183
아침_구매건수    0.672721
저녁_구매건수    0.643764
custid     0.218914
gender     0.094022
평균할부개월수   -0.037878
평균구매가격    -0.057376
주말방문비율    -0.096558
주구매코너     -0.143826
수입상품_구매비율 -0.210022

- 구매건수 컬럼이 전반적으로 높은 상관도를 보이고 있음 따라서 이를 기준으로 파생변수를 생성

In [17]:
data['아침구매액'] = data['총구매액']*(data['아침_구매건수'] /data['구매건수'])
data['점심구매액'] = data['총구매액']*(data['점심_구매건수'] /data['구매건수'])
data['저녁구매액'] = data['총구매액']*(data['저녁_구매건수'] /data['구매건수']) 
data['봄구매액']   = data['총구매액']*(data['봄_구매건수'] /data['구매건수'])
data['여름구매액'] = data['총구매액']*(data['여름_구매건수'] /data['구매건수']) 
data['가을구매액'] = data['총구매액']*(data['가을_구매건수'] /data['구매건수'])
data['겨울구매액'] = data['총구매액']*(data['겨울_구매건수'] /data['구매건수'])

In [18]:
data.head()

,custid,gender,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,...,저녁_구매건수,점심_구매건수,주구매코너,아침구매액,점심구매액,저녁구매액,봄구매액,여름구매액,가을구매액,겨울구매액
0,18,0,680100,15,45340,1.7,9,10,26.7,100.0,...,6.0,9.0,24,0.000000e+00,4.080600e+05,2.720400e+05,2.720400e+05,0.0,0.000000e+00,4.080600e+05
1,21,0,353450,9,39272,1.2,6,8,11.1,37.5,...,0.0,6.0,11,1.178167e+05,2.356333e+05,0.000000e+00,1.570889e+05,0.0,0.000000e+00,1.963611e+05
2,23,0,5671400,36,157539,2.8,22,16,5.6,37.5,...,11.0,15.0,15,1.575389e+06,2.363083e+06,1.732928e+06,1.890467e+06,0.0,1.102772e+06,2.678161e+06
3,26,0,1964000,28,70143,1.4,15,14,39.3,28.6,...,18.0,10.0,24,0.000000e+00,7.014286e+05,1.262571e+06,1.052143e+06,0.0,3.507143e+05,5.611429e+05
4,35,0,885000,5,177000,6.0,5,2,0.0,100.0,...,5.0,0.0,22,0.000000e+00,0.000000e+00,8.850000e+05,8.850000e+05,0.0,0.000000e+00,0.000000e+00

### 데이터 분할

In [19]:
from sklearn.model_selection import train_test_split

data = data.drop(['총구매액','구매건수','아침_구매건수','점심_구매건수','저녁_구매건수',
                      '봄_구매건수','여름_구매건수','가을_구매건수','겨울_구매건수'], axis=1)

dfX = data.drop(['gender'], axis=1) # axis=1 은 열
dfy = data['gender']

X_train, X_test, y_train, y_test = train_test_split(dfX, dfy, test_size = 0.25, random_state = 0)

display(X_train.shape, X_test.shape)

(3750, 15)

(1250, 15)

### 데이터 셈플링

In [20]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=0)
X_train_over,y_train_over = smote.fit_sample(X_train,y_train)
print('SMOTE 적용 전  데이터 세트: ', X_train.shape, y_train.shape)
print('SMOTE 적용 후  데이터 세트: ', X_train_over.shape, y_train_over.shape)
print('SMOTE 적용 후 데이터 비율: \n', pd.Series(y_train_over).value_counts())

SMOTE 적용 전  데이터 세트:  (3750, 15) (3750,)
SMOTE 적용 후  데이터 세트:  (5192, 15) (5192,)
SMOTE 적용 후 데이터 비율:
 1    2596
0    2596
Name: gender, dtype: int64

In [21]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train,y_train).score(X_test, y_test)

0.704

In [22]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train_over,y_train_over).score(X_test, y_test)

0.5

- 데이터 셈플링 작업을 하였지만 모델의 성능은 감소된걸 알 수 있다.

### 데이터 스케일링
- 특성별로 데이터의 스케일이 다를때 이를 방지

In [23]:
from sklearn.preprocessing import StandardScaler
# 각 feature의 평균을 0, 분상을 1로 변경

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

In [24]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train_scaled,y_train).score(X_test, y_test)

0.6072

- 데이터 스케일링 작업도 모델의 성능에 좋은 변화를 주지는 못하였다.

# 모델링

In [25]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train,y_train).score(X_test, y_test)

0.704

In [26]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()

tree.fit(X_train,y_train).score(X_test, y_test)

0.6032

In [27]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train,y_train).score(X_test, y_test)

0.636

In [28]:
from sklearn.ensemble import VotingClassifier

voting = VotingClassifier(
    estimators = [('logreg', logreg), ('tree', tree), ('knn', knn)],
    voting = 'hard')

voting.fit(X_train,y_train).score(X_test, y_test)

0.6864

In [29]:
from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(base_estimator=KNeighborsClassifier(), random_state=0, n_estimators=200)
bagging.fit(X_train, y_train).score(X_test, y_test)

0.6472

In [30]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(n_estimators=200, random_state=0)
ada.fit(X_train, y_train).score(X_test, y_test)

0.6696

In [31]:
from sklearn.ensemble import GradientBoostingClassifier

gbm = GradientBoostingClassifier(n_estimators=200, random_state=0)
gbm.fit(X_train, y_train).score(X_test, y_test)

0.6736

In [32]:
from lightgbm import LGBMClassifier

lgb = LGBMClassifier(n_estimaotrs = 200, random_state=0)
lgb.fit(X_train, y_train).score(X_test, y_test)

[LightGBM] [Warning] Unknown parameter: n_estimaotrs

0.688

# 데이터 검증

In [33]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

model = SVC()
scores = cross_val_score(model, X_train, y_train); scores

array([0.692     , 0.692     , 0.69733333, 0.69866667, 0.69333333])

In [34]:
print("Mean: {:.3f}\nStd: {:.3f}\nMin: {:.3f}\nMax: {:.3f}".format(
    scores.mean(), scores.std(), scores.min(), scores.max()))
# 분산이 작으면 Overfitting 이 적다
# 과적합 : 100~90   적정적합 : 90~65    과소적합 : 65~

Mean: 0.695
Std: 0.003
Min: 0.692
Max: 0.699

# 예측 데이터셋 생성

In [35]:
test = test.fillna(0)
obj = ['주구매코너']
test[obj] = test[obj].apply(lambda x: x.astype('category').cat.codes)

In [36]:
test['아침구매액'] = test['총구매액']*(test['아침_구매건수'] /test['구매건수'])
test['점심구매액'] = test['총구매액']*(test['점심_구매건수'] /test['구매건수'])
test['저녁구매액'] = test['총구매액']*(test['저녁_구매건수'] /test['구매건수']) 
test['봄구매액']   = test['총구매액']*(test['봄_구매건수'] /test['구매건수'])
test['여름구매액'] = test['총구매액']*(test['여름_구매건수'] /test['구매건수']) 
test['가을구매액'] = test['총구매액']*(test['가을_구매건수'] /test['구매건수'])
test['겨울구매액'] = test['총구매액']*(test['겨울_구매건수'] /test['구매건수'])

In [37]:
test = test.drop(['총구매액','구매건수','아침_구매건수','점심_구매건수','저녁_구매건수',
                      '봄_구매건수','여름_구매건수','가을_구매건수','겨울_구매건수'], axis=1)

In [40]:
test['gender'] = logreg.predict(test.loc[:,'custid':'겨울구매액'])

In [41]:
test

,custid,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,주구매코너,아침구매액,점심구매액,저녁구매액,봄구매액,여름구매액,가을구매액,겨울구매액,gender
0,100001,137560,2.2,19,16,12.0,31.2,15,1.788280e+06,1.513160e+06,137560.000000,9.629200e+05,1.238040e+06,687800.000000,5.502400e+05,0
1,100002,53156,1.3,18,29,0.0,20.7,13,2.126246e+05,1.328904e+06,531561.538462,5.315615e+05,4.252492e+05,691030.000000,4.252492e+05,0
2,100003,59264,1.8,14,12,0.0,41.7,13,1.777909e+05,1.066745e+06,59263.636364,1.777909e+05,3.555818e+05,355581.818182,4.148455e+05,0
3,100004,145577,1.7,31,22,37.0,50.0,8,0.000000e+00,6.114216e+06,582306.260870,1.310189e+06,2.474802e+06,727882.826087,2.183648e+06,0
4,100005,49909,2.3,13,9,11.5,22.2,9,0.000000e+00,1.297640e+06,0.000000,2.495462e+05,1.497277e+05,898366.153846,0.000000e+00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,104996,134138,1.4,5,4,0.0,75.0,14,1.341380e+05,4.024140e+05,134138.000000,2.682760e+05,0.000000e+00,134138.000000,2.682760e+05,0
4996,104997,48362,1.8,10,7,7.7,42.9,17,0.000000e+00,4.836154e+05,145084.615385,4.836154e+04,3.385308e+05,0.000000,2.418077e+05,0
4997,104998,80077,1.8,7,7,0.0,42.9,14,0.000000e+00,9.609230e+05,0.000000,4.804615e+05,8.007692e+04,320307.666667,8.007692e+04,0
4998,104999,56186,1.7,12,9,14.3,55.6,24,1.123714e+05,4.494857e+05,224742.857143,2.247429e+05,1.685571e+05,0.000000,3.933000e+05,0
4999,105000,33790,1.6,23,35,10.5,22.9,14,3.716948e+05,2.061216e+06,135161.736842,3.041139e+05,8.109704e+05,777179.986842,6.758087e+05,0

In [42]:
test.to_csv("logreg.csv", encoding='cp949', index=False)